import { describe, it, expect } from "vitest";
import {
  containsProviderHint,
  sanitizeGeneratedCode,
  sanitizeText,
  stripComments,
} from "@/lib/ai/sanitize";

describe("stripComments", () => {
  it("removes line and block comments", () => {
    const code = `// Generated by SomeVendor v3
/* multi
   line */
export default function Scene() { return null; }`;
    const out = stripComments(code);
    expect(out).not.toContain("Generated by");
    expect(out).not.toContain("multi");
    expect(out).toContain("export default function Scene()");
  });

  it("does NOT mistake a // inside a string literal for a comment", () => {
    const code = `export default function S() {
  const url = "https://example.com/logo.svg";
  return url;
}`;
    expect(stripComments(code)).toContain("https://example.com/logo.svg");
  });

  it("leaves unparseable source untouched", () => {
    const broken = "export default function ( {{{";
    expect(stripComments(broken)).toBe(broken);
  });

  it("removes a JSX comment expression container", () => {
    const code = `export default function S() {
  return <div>{/* authored by a vendor */}<span>hi</span></div>;
}`;
    const out = stripComments(code);
    expect(out).not.toContain("authored by a vendor");
    expect(out).toContain("<span>hi</span>");
  });
});

describe("sanitizeText", () => {
  it("neutralises vendor names", () => {
    expect(sanitizeText("Generated with Claude Sonnet")).not.toMatch(/claude/i);
    expect(sanitizeText("powered by Gemini")).not.toMatch(/gemini/i);
    expect(sanitizeText("via OpenRouter")).not.toMatch(/openrouter/i);
  });

  it("neutralises model ids", () => {
    const out = sanitizeText("model: anthropic/claude-sonnet-4.6");
    expect(out).not.toContain("anthropic/claude-sonnet-4.6");
    expect(containsProviderHint(out)).toBe(false);
  });

  it("neutralises the generic self-description", () => {
    expect(sanitizeText("As a large language model, I...")).not.toMatch(
      /large language model/i,
    );
  });
});

describe("sanitizeGeneratedCode", () => {
  it("strips a vendor signature comment from generated source", () => {
    const code = `// Generated by anthropic/claude-sonnet-4.6
export default function Scene({ params }) {
  return <h1>{params.headline}</h1>;
}`;
    const out = sanitizeGeneratedCode(code);
    expect(containsProviderHint(out)).toBe(false);
    expect(out).toContain("params.headline");
  });

  /**
   * The load-bearing case: a user is entitled to put a vendor's name on screen.
   * "Promo for OpenAI" must render as OpenAI — hint-stripping protects OUR
   * provider identity, it does not censor the user's content.
   */
  it("preserves vendor names that are the USER's content, not the model's", () => {
    const code = `export default function Scene({ params }) {
  return <h1>{params.headline}</h1>;
}`;
    const out = sanitizeGeneratedCode(code);
    expect(out).toContain("params.headline");
    // The user's words live in params, which this function never touches.
    const userParams = [
      { key: "headline", label: "Headline", type: "text" as const, default: "OpenAI is hiring" },
    ];
    expect(userParams[0].default).toBe("OpenAI is hiring");
  });
});

describe("containsProviderHint", () => {
  it("is stateless across calls (no lastIndex leakage)", () => {
    const s = "claude";
    expect(containsProviderHint(s)).toBe(true);
    expect(containsProviderHint(s)).toBe(true);
    expect(containsProviderHint(s)).toBe(true);
  });

  it("is false for ordinary motion code", () => {
    expect(
      containsProviderHint(`export default function S({ params }) {
  return <div style={{ opacity: params.o }} />;
}`),
    ).toBe(false);
  });
});
